const root=document.getElementById('forest-rts');if(!root)return;
const $=id=>root.querySelector('#r-'+id),canvas=$('field'),ctx=canvas.getContext('2d'),mini=$('mini'),mc=mini.getContext('2d'),portrait=$('portrait'),pc=portrait.getContext('2d');
let online=null;
let world=new World();const camera=new Camera();
let player=0,game,selected=new Set(),selectedBuilding=null,mode=null,buildKind=null,drag=null,panMode=false,pointerInside=false,mouse={x:-999,y:-999},keys=new Set(),active=false,last=0,uiElapsed=0,soundContext=null,lastSoundId=0,lastEventId=0,dpr=1;
const saved=window.openai?.widgetState?.modelContent;if(Number.isInteger(saved?.clan)&&saved.clan>=0&&saved.clan<4)player=saved.clan;
if(typeof window.openai?.widgetState?.privateContent?.sound==='boolean')$('sound').checked=window.openai.widgetState.privateContent.sound;
function persist(){window.openai?.setWidgetState({modelContent:{clan:player,prototype:'village-economy'},privateContent:{sound:$('sound').checked}})?.catch(()=>{});}
function message(text){$('message').textContent=text;}
function own(){return game.alive(player).filter(u=>selected.has(u.id));}
function ownWorkers(){return own().filter(u=>u.worker);}
function centerHome(){camera.center({x:STARTS[player].x+(player===0||player===3?80:-80),y:STARTS[player].y+80});}
function cancelMode(){mode=null;buildKind=null;$('placement').hidden=true;updateUI();}
function choose(units){selectedBuilding=null;selected=new Set(units.map(u=>u.id));mode=null;buildKind=null;updateUI();}
function reset(){$('tech').hidden=true;world=new World();game=new EconomyBattle(player,world);selected=new Set([game.workers()[0].id]);selectedBuilding=null;camera.zoom=1.15;centerHome();mode=null;buildKind=null;drag=null;panMode=false;pointerInside=false;keys.clear();lastSoundId=0;lastEventId=0;$('pan').setAttribute('aria-pressed','false');$('start').textContent='เริ่มหมู่บ้าน';$('start').disabled=false;$('clan').disabled=false;$('intro').hidden=false;$('intro').innerHTML='<small>THE VILLAGE COMES FIRST</small><strong>สร้างหมู่บ้าน ก่อนสร้างกองทัพ</strong><span>ชาวบ้าน 6 คน · นักรบ 4 คน · ข้าว 360 · น้ำ 180</span><span>กด “เริ่มหมู่บ้าน” เพื่อทดลองเก็บเสบียงและก่อสร้าง</span>';message('เลือกชาวบ้านเพื่อเปิดเมนูก่อสร้างด้านล่างขวา');updateUI();draw();}
function audioUnlock(){try{const Audio=window.AudioContext||window.webkitAudioContext;if(!soundContext&&Audio)soundContext=new Audio();soundContext?.resume().catch(()=>{});}catch{}}
function beep(){if(!$('sound').checked||!soundContext)return;try{for(let i=0;i<2;i++){const o=soundContext.createOscillator(),g=soundContext.createGain(),t=soundContext.currentTime+i*.18;o.type='triangle';o.frequency.value=i?610:790;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.10,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+.15);o.connect(g);g.connect(soundContext.destination);o.start(t);o.stop(t+.16);}}catch{}}
function jumpAlert(){const a=game.alerts.at(-1);if(a){camera.center(a);message('กล้องย้ายมาที่จุดถูกโจมตีแล้ว');}}
function unitHit(u,p){return Math.abs(u.x-p.x)<24/camera.zoom&&p.y>=u.y-(u.form?75:43)&&p.y<=u.y+14/camera.zoom;}
function unitName(u){return unitTitle(u)+(u.worker?' '+CLANS[u.team].name:' · ขั้น '+u.tier);}
function jobText(u){if(u.job?.type==='train')return 'กำลังเดินเข้าโรงฝึก';if(!u.worker)return u.order==='hold'?'ตั้งรับ':u.order==='move'?'กำลังเดิน':'กำลังรบ';if(!u.job)return u.order==='move'?'กำลังเดิน':'ว่าง · รอคำสั่ง';if(u.job.type==='gather'){const r=game.resources.find(r=>r.id===u.job.resourceId);return u.job.phase==='return'?'ขนเสบียงกลับคลัง':r?.type==='rice'?(r.amount>0?'กำลังเกี่ยวข้าว':'รอข้าวงอกใหม่ · '+Math.ceil(r.cycle)+' วิ'):'กำลังตักน้ำ';}return u.job.type==='repair'?'กำลังซ่อมอาคาร':u.job.type==='build'?'กำลังก่อสร้าง':'กำลังเดินเข้าโรงฝึก';}
function updateUI(){updateBaseUI();online?.updateHUD();}
function updateBaseUI(){if(!game)return;const list=own(),workers=list.filter(u=>u.worker),r=game.stock[player],cap=game.storage(),c=CLANS[player],b=selectedBuilding?.hp>0?selectedBuilding:null;if(!b)selectedBuilding=null;
  $('rice').textContent=Math.floor(r.rice);$('water').textContent=Math.floor(r.water);$('rice-cap').textContent='/ '+cap.rice;$('water-cap').textContent='/ '+cap.water;
  for(const type of ['rice','water'])$(type+'-workers').textContent=(type==='rice'?'คนเกี่ยว ':'คนตัก ')+game.workers().filter(u=>u.job?.type==='gather'&&game.resources.find(r=>r.id===u.job.resourceId)?.type===type).length;
  $('pop').textContent=game.population()+' / '+game.capacity();$('pop-detail').textContent='ชาวบ้าน '+game.workers().length+' · ทหาร '+game.warriors().length;$('clock').textContent=String(Math.floor(game.t/60)).padStart(2,'0')+':'+String(Math.floor(game.t%60)).padStart(2,'0');$('zoom').textContent=Math.round(camera.zoom*100)+'%';$('base-label').textContent='ฐาน '+Math.ceil(game.bases[player].hp)+' / 1800';$('raid').disabled=!game.running||game.over||(game.war&&game.alive().some(u=>u.raid&&u.team!==player));
  $('worker-commands').hidden=!!b||!workers.length||list.some(u=>!u.worker);$('army-commands').hidden=!!b||!list.some(u=>!u.worker);$('building-commands').hidden=!b;$('empty-commands').hidden=!!b||!!list.length;
  $('command-title').textContent=b?'จัดการ'+(b.kind==='hq'?'ศาลาบัญชาการ':BUILDINGS[b.kind].name):list.some(u=>!u.worker)?'คำสั่งกองทัพ'+(workers.length?' · มีชาวบ้านในกลุ่ม':''):'งานชาวบ้านและก่อสร้าง';
  let hp=0,max=1;
  if(b){hp=b.hp;max=b.max;$('selection-type').textContent='สิ่งก่อสร้าง';$('selection-count').textContent=b.complete?'พร้อมใช้งาน':'กำลังก่อสร้าง';$('selected').textContent=b.kind==='hq'?'ศาลาบัญชาการ':BUILDINGS[b.kind].name;$('selection-desc').textContent='ตระกูล'+c.name;$('job').textContent=b.complete?(b.kind==='hut'?'เกิดชาวบ้านอัตโนมัติ':'สร้างเสร็จแล้ว'):'ความคืบหน้า '+Math.floor(b.progress*100)+'%';$('cargo').textContent=b.kind==='hut'?'กำลังคน '+game.population()+' / '+game.capacity():'';updateBuildingUI(b);
  }else{hp=list.reduce((s,u)=>s+u.hp,0);max=list.reduce((s,u)=>s+u.max,0)||1;$('selection-type').textContent=workers.length?'ชาวบ้าน':'กองทัพ';$('selection-count').textContent='เลือก '+list.length+' คน';$('selected').textContent=list.length===1?unitName(list[0]):list.length?list.length+' คน · '+c.name:'ยังไม่เลือกยูนิต';$('selection-desc').textContent=workers.length?'เกี่ยวข้าว · ตักน้ำ · ก่อสร้าง':'ประชิด '+list.filter(u=>!u.ranged&&!u.worker).length+' · ยิงไกล '+list.filter(u=>u.ranged).length;$('job').textContent=list.length===1?jobText(list[0]):workers.length?'ชาวบ้าน '+workers.length+' คนพร้อมรับคำสั่ง':'คลิกทหารหรือกด [1]';const cargo=list.reduce((s,u)=>s+(u.cargo||0),0);$('cargo').textContent=workers.length?'ถือเสบียง '+Math.floor(cargo)+' / '+workers.length*12:'Q สกิลตระกูล · E ยิงระดม';}
  $('health').textContent=Math.ceil(hp)+' / '+(max===1&&!list.length&&!b?0:max);$('hp-bar').style.width=(hp/max*100)+'%';
  for(const button of $('build-grid').children){const d=BUILDINGS[button.dataset.kind];button.disabled=!game.running||game.over||!workers.length||!game.affordable(d)||!!game.buildRequirement(button.dataset.kind);button.title=game.buildRequirement(button.dataset.kind)||d.description;button.classList.toggle('armed',buildKind===button.dataset.kind);}
  for(const id of ['gather-rice','gather-water','worker-hold'])$(id).disabled=!game.running||game.over||!workers.length;
  $('skill-name').textContent='Q · '+c.skill+(game.cooldowns[player]>0?' '+Math.ceil(game.cooldowns[player])+'s':'');$('skill-desc').textContent=c.desc;$('volley-desc').textContent=game.volleys[player]>0?'พร้อมอีก '+Math.ceil(game.volleys[player])+' วิ':'พลธนูยิง 3 นัด · CD 10 วิ';$('skill').disabled=!game.running||game.over||!list.some(u=>!u.worker)||game.cooldowns[player]>0;$('volley').disabled=!game.running||game.over||!list.some(u=>u.ranged)||game.volleys[player]>0;
  updateTrainingOptions(list);
  const crop=game.resources.find(r=>r.id==='rice-'+player);if(crop){const f=crop.stage==='ripe'?crop.amount/crop.max:crop.stage==='growing'?1-crop.cycle/RICE_CYCLE.growing:0;$('crop-status').innerHTML='<b>🌾 '+(crop.stage==='ripe'?'ข้าวในนา '+Math.ceil(crop.amount)+' / '+crop.max:crop.stage==='fallow'?'เกี่ยวหมดแล้ว · พักดิน':'ต้นกล้ากำลังงอก')+'</b><small>'+(crop.stage==='ripe'?'เกี่ยวแล้ว '+(48-crop.patches.filter(n=>n>.001).length)+' / 48 กอ · คลิกดูนา':'เก็บได้อีกใน '+Math.ceil(crop.cycle+(crop.stage==='fallow'?RICE_CYCLE.growing:0))+' วินาที')+'</small><i style="width:'+Math.round(f*100)+'%"></i>';}
  const roster=$('roster'),key=list.map(u=>u.id+':'+u.worker+':'+u.tier+':'+u.role).join(',');if(roster.dataset.key!==key){roster.dataset.key=key;roster.innerHTML='';for(const u of list){const button=document.createElement('button');button.className='cursor-interaction';button.dataset.id=u.id;button.setAttribute('aria-label',unitName(u)+' หมายเลข '+(u.id+1));button.innerHTML='<canvas width=40 height=40 aria-hidden=true></canvas><i></i>'; button.onclick=()=>choose([u]);button.ondblclick=()=>camera.center(u);roster.append(button);}}for(const button of roster.children){const u=game.units.find(u=>u.id===Number(button.dataset.id));button.querySelector('i').style.width=(u.hp/u.max*84)+'%';}
  const p=camera.world({x:camera.w/2,y:camera.h/2}),near=STARTS.findIndex(b=>dist(b,p)<620);$('location').textContent=(near>=0?'เขตฐาน'+CLANS[near].name:'ป่าชั้นใน')+' · '+Math.round(p.x)+', '+Math.round(p.y)+(!game.seen[world.cell(p)]?' · ยังไม่ได้สำรวจ':'');$('objective').textContent=game.economyStats.trained?'กองทัพพร้อม '+game.warriors().length+' คน · พร้อมแล้วกดทดสอบศัตรูบุก':game.economyStats.built?'คลิกโรงฝึกที่สร้างเสร็จ → กดฝึกทหาร':game.economyStats.rice+game.economyStats.water>0?'เสบียงเข้าคลังแล้ว · เลือกชาวบ้านแล้วสร้างโรงฝึก':'เลือกชาวบ้าน → เกี่ยวข้าว / ตักน้ำ → สร้างโรงฝึก';
  const alert=game.alerts.at(-1);$('alert').hidden=!alert||game.t-alert.t>14;if(alert&&alert.id>lastSoundId){lastSoundId=alert.id;beep();message('กองกำลังถูกโจมตี! กด Space เพื่อไปดู');}
  const event=game.events.at(-1);if(event&&event.id>lastEventId){lastEventId=event.id;message(event.text);}if(game.over){$('start').disabled=true;$('intro').hidden=false;$('intro').innerHTML='<small>จบการรบ</small><strong>'+(game.bases[player].hp<=0?'ฐานของคุณถูกทำลาย':'คุณครองป่าเงาจันทร์')+'</strong><span>กดเริ่มใหม่เพื่อทดลองอีกครั้ง</span>';}
  const item=b||list[0];$('clan-name').textContent='เผ่า'+c.name+' · P'+(player+1);$('stat-attack').textContent='⚔ โจมตี '+Math.round((item?.damage||0)*(item?.form==='wolf'&&item.awakened>0?1.25:1));$('stat-range').textContent='ระยะ '+(item?.range||0);$('stat-speed').textContent='ความเร็ว '+(Math.round((item?.speed||0)*10)/10);const cargo=list.reduce((sum,u)=>sum+(u.cargo||0),0);$('energy-name').textContent=workers.length?'สัมภาระ':'สกิลตระกูล';$('energy-value').textContent=workers.length?Math.floor(cargo)+' / '+workers.length*12:game.cooldowns[player]>0?Math.ceil(game.cooldowns[player])+' วิ':'พร้อมใช้';$('energy-bar').style.width=(workers.length?cargo/(workers.length*12)*100:game.cooldowns[player]>0?0:100)+'%';drawPortrait(item);if(artReady)paintCommandIcons();
}
function updateBuildingUI(b){const d=BUILDINGS[b.kind],training=TRAINING[b.kind];$('building-desc').textContent=b.kind==='hq'?'ศูนย์บัญชาการและจุดส่งข้าว–น้ำ · ปกป้องฐานเพื่ออยู่รอด':d.description;$('train').hidden=!training||!b.complete;$('cancel-build').hidden=b.complete;$('resume-build').hidden=b.complete;$('cancel-queue').hidden=!b.queue.length;
  if(training){$('train').hidden=!b.complete||b.kind==='warhall';$('train').innerHTML='ฝึก'+training.name+' · '+training.rice+' ข้าว / '+training.water+' น้ำ<small>ใช้ชาวบ้าน 1 คน · '+training.seconds+' วินาที · คิว '+b.queue.length+'/3</small>';$('train').disabled=!game.running||!game.affordable(training)||b.queue.length>=3||!game.workers().some(u=>u.job?.type!=='train'&&u.job?.type!=='build');}
  $('upgrade-building').hidden=!training||!b.complete;if(training){const u=game.warriors().filter(u=>game.trainingRecipe(u,b.kind)?.tier>1).sort((a,c)=>dist(a,b)-dist(c,b))[0],d=u&&game.trainingRecipe(u,b.kind);$('upgrade-building').textContent=d?'★ '+unitTitle(u)+' → '+d.name+' · '+d.rice+' ข้าว / '+d.water+' น้ำ · '+d.seconds+' วิ':'ยังไม่มีทหารที่พร้อมฝึกวิชานี้ · ดูสายพัฒนา';$('upgrade-building').disabled=!game.running||game.over||!d||b.queue.length>=3||!game.affordable(d);}
  $('tower-upgrade').hidden=b.kind!=='tower'||!b.complete;if(b.kind==='tower'){const next=TOWER_LEVELS[b.level+1];$('building-desc').textContent='ป้อมธนูระดับ '+b.level+' · โจมตี '+b.damage+' · ระยะ '+b.range+' · ยิงอัตโนมัติ';$('tower-upgrade').textContent=b.upgrading?'กำลังอัปเกรด · '+Math.ceil(b.upgrading.remaining)+' วิ':next?'↑ ระดับ '+(b.level+1)+' · '+next.rice+' ข้าว / '+next.water+' น้ำ · '+next.seconds+' วิ':'ป้อมระดับ 3 · สูงสุดแล้ว';$('tower-upgrade').disabled=!game.running||game.over||!!b.upgrading||!next||!game.affordable(next);}
  $('repair').hidden=!b.complete||b.hp>=b.max;$('repair').disabled=!game.running||game.over||!game.workers().some(u=>!u.job);
  let text='';if(!b.complete){const builders=game.workers().filter(u=>u.job?.buildingId===b.id).length;text='<div class="r-queue-item"><span>คนงาน '+builders+' คน</span><span>'+Math.floor(b.progress*100)+'%</span></div><div class="r-production-track"><i style="width:'+b.progress*100+'%"></i></div>';if(!builders)text+='<span>ไม่มีคนงาน · ส่งชาวบ้านมาสร้างต่อ</span>';}
  else if(b.kind==='hut'){const full=game.population()>=game.capacity();text='<div class="r-queue-item"><span>ชาวบ้านใหม่ · ไม่เสียเสบียง</span><span>'+(full?'กำลังคนเต็ม':Math.ceil(30-b.spawn)+' วิ')+'</span></div><div class="r-production-track"><i style="width:'+b.spawn/30*100+'%"></i></div>';}
  else if(training){text=b.queue.length?b.queue.map((q,i)=>{const u=game.units.find(u=>u.id===q.unitId);return'<div class="r-queue-item"><span>'+(i+1)+'. '+q.recipe.name+'</span><span>'+(!u?.inTraining?'เดินเข้าโรงฝึก':i?'รอคิว':Math.ceil(q.remaining)+' วิ')+'</span></div><div class="r-production-track"><i style="width:'+(1-q.remaining/q.total)*100+'%"></i></div>';}).join(''):'<div class="r-queue-item">ยังไม่มีคิว · กดฝึกเพื่อส่งชาวบ้านเข้าโรงฝึก</div>';}
  else if(b.kind==='tower')text='<div class="r-queue-item">วงสีทองคือระยะยิง · เปิดเมนูเพื่อทดสอบศัตรูบุก</div>';else if(b.kind==='well')text='<div class="r-queue-item">เลือกชาวบ้าน แล้วคลิกขวาที่บ่อน้ำเพื่อเริ่มตัก</div>';else if(b.kind==='store')text='<div class="r-queue-item">ความจุรวม '+game.storage().rice+' ข้าว / '+game.storage().water+' น้ำ</div>';$('production').innerHTML=text;
}
function beginBuild(kind){if(!game.running||!ownWorkers().length)return;buildKind=kind;mode='build';const d=BUILDINGS[kind];$('placement').hidden=false;$('placement').textContent=d.name+' · '+d.rice+' ข้าว / '+d.water+' น้ำ · คลิกวาง / Esc ยกเลิก';message(d.description);updateUI();}
function quickGather(type){const units=ownWorkers();if(!game.running||!units.length)return;const resources=game.resources.filter(r=>r.type===type&&game.visibleAt(r)&&(!r.buildingId||game.structures.some(b=>b.id===r.buildingId&&b.hp>0)));let count=0;const groups=new Map();for(const u of units){const r=[...resources].sort((a,b)=>dist(a,u)-dist(b,u))[0];if(r){if(!groups.has(r))groups.set(r,[]);groups.get(r).push(u.id);}}for(const [resource,ids]of groups)count+=game.assignGather(ids,resource);message(count?count+' คนเริ่ม'+(type==='rice'?'เกี่ยวข้าว':'ตักน้ำ')+' · ทรัพยากรเพิ่มเมื่อส่งถึงคลัง':'ยังไม่พบแหล่งทรัพยากรในพื้นที่ที่สำรวจ');updateUI();}
function skill(){if(!game.running||!own().some(u=>!u.worker))return;if(player===1&&game.cooldowns[player]<=0){mode='poison';message('คลิกพื้นที่เพื่อปล่อยหมอกพิษ');}else message(game.cast(player,[...selected])?CLANS[player].skill+' ทำงานแล้ว':'สกิลไม่พร้อม หรือไม่มีศัตรูในระยะ');updateUI();}
function command(p){if(!game.running||game.over)return;if(!own().length){message('เลือกยูนิตก่อนออกคำสั่ง');return;}if(mode==='poison'){message(game.cast(player,[...selected],p)?'ปล่อยหมอกพิษแล้ว':'สกิลไม่พร้อม');mode=null;return;}const workers=ownWorkers(),building=game.structures.find(b=>b.hp>0&&b.team===player&&Math.abs(p.x-b.x)<b.w/2+15&&Math.abs(p.y-b.y)<b.h/2+30),resource=game.resources.find(r=>game.visibleAt(r)&&(dist(r,p)<(r.type==='rice'?85:65)||(r.visualX!==undefined&&Math.hypot((p.x-r.visualX)/60,(p.y-r.visualY)/40)<=1)));if(building&&TRAINING[building.kind]&&mode!=='move'&&mode!=='attack'){const result=game.train(building,[...selected]);message(result.ok?'ยูนิตกำลังเดินเข้าโรงฝึก':result.reason);updateUI();return;}if(workers.length&&mode!=='move'&&mode!=='attack'){if(building?.complete&&building.hp<building.max){message(game.repair(building,[...selected])?'คนงานกำลังเดินมาซ่อมอาคาร':'ซ่อมไม่ได้');return;}if(building&&!building.complete){game.assignBuild([...selected],building);message('ส่งชาวบ้านสร้างต่อ');return;}if(building?.kind==='well'&&building.complete){const source=game.resources.find(r=>r.buildingId===building.id);game.assignGather([...selected],source);message('เริ่มตักน้ำจากบ่อและขนกลับคลัง');return;}if(resource){game.assignGather([...selected],resource);message('เริ่ม'+(resource.type==='rice'?'เกี่ยวข้าว':'ตักน้ำ')+'และขนกลับคลังอัตโนมัติ');return;}}
  const enemy=game.targets(player).find(u=>game.visibleAt(u)&&(u.building?Math.abs(p.x-u.x)<u.w/2+12&&Math.abs(p.y-u.y)<u.h/2+25:unitHit(u,p)));if(enemy&&mode!=='move'){game.issue([...selected],'target',enemy);message('โจมตี '+CLANS[enemy.team].name);}else{const army=own().filter(u=>!u.worker).map(u=>u.id),peasants=workers.map(u=>u.id);if(army.length)game.issue(army,mode==='move'?'move':'advance',p);if(peasants.length)game.issue(peasants,mode==='attack'?'advance':'move',p);message(army.length&&mode!=='move'?'เดินบุก · โจมตีเป้าหมายตามโหมดที่เลือกอัตโนมัติ':'เคลื่อนพลไปยังจุดที่เลือก');}game.effect('order',p.x,p.y,'#ead59a',1);mode=null;updateUI();}
for(const [kind,d]of Object.entries(BUILDINGS)){const b=document.createElement('button');b.type='button';b.className='cursor-interaction';b.dataset.kind=kind;b.setAttribute('aria-label','สร้าง'+d.name+' '+d.rice+' ข้าว '+d.water+' น้ำ');b.innerHTML='<canvas width=72 height=44 aria-hidden=true></canvas><b><span class="r-build-icon">'+d.icon+'</span>'+d.name+'</b><small>🌾 '+d.rice+' · ◈ '+d.water+' · '+d.seconds+'s</small>';b.onclick=()=>beginBuild(kind);$('build-grid').append(b);}
$('clan').value=player;$('clan').onchange=()=>{if(online?.active)return;player=Number($('clan').value);persist();reset();};$('start').onclick=()=>{if(online?.active){online.open();return;}audioUnlock();game.started=true;game.running=!game.running;$('start').textContent=game.running?'พัก [P]':'เล่นต่อ';$('clan').disabled=true;$('intro').hidden=true;message(game.running?'เริ่มหมู่บ้านแล้ว · เลือกชาวบ้านแล้วกดเกี่ยวข้าวหรือตักน้ำ':'พักเกม · ยังเลื่อนกล้องและเลือกสิ่งต่าง ๆ ได้');updateUI();};$('reset').onclick=()=>{if(!online?.active)reset();};$('home').onclick=centerHome;$('plus').onclick=()=>camera.scale(camera.zoom*1.15);$('minus').onclick=()=>camera.scale(camera.zoom/1.15);$('alert').onclick=jumpAlert;$('sound').onchange=()=>{audioUnlock();persist();};$('all').onclick=()=>choose(game.warriors());$('workers').onclick=()=>choose(game.workers());$('idle').onclick=()=>{const u=game.workers().find(u=>!u.job&&u.order==='hold');if(u){choose([u]);camera.center(u);}else message('ไม่มีชาวบ้านว่าง');};$('gather-rice').onclick=()=>quickGather('rice');$('gather-water').onclick=()=>quickGather('water');$('cancel').onclick=cancelMode;$('worker-hold').onclick=$('hold').onclick=()=>{game.issue([...selected],'hold');message('หยุดและตั้งรับ');updateUI();};$('move').onclick=()=>{mode='move';message('คลิกปลายทาง');};$('attack').onclick=()=>{mode='attack';message('คลิกปลายทางเพื่อเดินบุก');};$('skill').onclick=skill;$('volley').onclick=()=>{message(game.volley(player,[...selected])?'ยิงระดม!':'เลือกพลธนูที่มีศัตรูในระยะ');updateUI();};$('raid').onclick=()=>{if(online?.active)return;game.callRaid();updateUI();};$('train').onclick=()=>{const result=game.train(selectedBuilding);message(result.ok?'ชาวบ้านเดินเข้าโรงฝึกแล้ว':result.reason);updateUI();};$('cancel-queue').onclick=()=>{game.cancelTraining(selectedBuilding);updateUI();};$('cancel-build').onclick=()=>{game.cancelBuilding(selectedBuilding);selectedBuilding=null;updateUI();};$('resume-build').onclick=()=>{const u=game.workers().find(u=>!u.job);if(u){game.assignBuild([u.id],selectedBuilding);message('ชาวบ้านกำลังเดินมาสร้างต่อ');}else message('ไม่มีชาวบ้านว่าง · เลือกชาวบ้านแล้วคลิกขวาที่อาคารเพื่อส่งมาสร้าง');};$('pan').onclick=()=>{panMode=!panMode;$('pan').setAttribute('aria-pressed',String(panMode));};$('guide-button').onclick=()=>{$('guide').hidden=!$('guide').hidden;$('guide-button').setAttribute('aria-expanded',String(!$('guide').hidden));};
function local(e,el=canvas){const r=el.getBoundingClientRect();return{x:(e.clientX-r.left)*(el===mini?240:camera.w)/r.width,y:(e.clientY-r.top)*(el===mini?180:camera.h)/r.height};}
canvas.addEventListener('contextmenu',e=>{e.preventDefault();if(buildKind){cancelMode();return;}command(camera.world(local(e)));});canvas.addEventListener('pointerenter',e=>{mouse=local(e);pointerInside=true;});canvas.addEventListener('pointerleave',()=>pointerInside=false);canvas.addEventListener('pointerdown',e=>{audioUnlock();if(e.button===2)return;$('workers').focus({preventScroll:true});const p=local(e);drag={kind:e.button===1||panMode?'pan':'select',start:p,end:p,origin:{x:camera.x,y:camera.y},shift:e.shiftKey};canvas.setPointerCapture(e.pointerId);e.preventDefault();});canvas.addEventListener('pointermove',e=>{mouse=local(e);if(!drag)return;drag.end=mouse;if(drag.kind==='pan'){camera.x=drag.origin.x+(drag.start.x-mouse.x)/camera.zoom;camera.y=drag.origin.y+(drag.start.y-mouse.y)/camera.zoom;camera.clamp();}});canvas.addEventListener('pointerup',e=>{if(e.button===2||!drag)return;const d=drag;drag=null;if(d.kind==='pan')return;const p=local(e),wp=camera.world(p);if(buildKind){const result=game.build(buildKind,wp,[...selected]);if(result.ok){selectedBuilding=result.building;selected.clear();cancelMode();}else message(result.reason);updateUI();return;}if(mode&&dist(d.start,p)<=7){command(wp);return;}if(dist(d.start,p)>7)message('เลือกกลุ่มแล้ว · คลิกขวาเพื่อเดินบุก · เลือกชนิดเป้าหมายได้ในแผงคำสั่ง');mode=null;selectedBuilding=null;if(!d.shift)selected.clear();if(dist(d.start,p)>7){const a=camera.world(d.start);for(const u of game.alive(player))if(u.x>=Math.min(a.x,wp.x)&&u.x<=Math.max(a.x,wp.x)&&u.y>=Math.min(a.y,wp.y)&&u.y<=Math.max(a.y,wp.y))selected.add(u.id);}else{const u=game.alive(player).filter(u=>unitHit(u,wp)).sort((a,b)=>dist(a,wp)-dist(b,wp))[0];if(u)selected.add(u.id);else selectedBuilding=game.structures.find(b=>b.hp>0&&b.team===player&&Math.abs(b.x-wp.x)<b.w/2+18&&wp.y>b.y-b.h-35&&wp.y<b.y+b.h/2+18)||null;}updateUI();});canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();camera.scale(camera.zoom*Math.exp(-e.deltaY*.0012),local(e));},{passive:false});
let miniDrag=false;function moveMini(e){const p=local(e,mini);camera.center({x:p.x/240*W,y:p.y/180*H});}mini.addEventListener('pointerdown',e=>{if(e.button!==0)return;miniDrag=true;mini.setPointerCapture(e.pointerId);moveMini(e);e.preventDefault();});mini.addEventListener('pointermove',e=>{if(miniDrag)moveMini(e);});mini.addEventListener('pointerup',()=>miniDrag=false);mini.addEventListener('pointercancel',()=>miniDrag=false);
function keydown(e){if(!$('tech').hidden){if(e.key==='Escape')closeTech();return;}if(!active||!root.isConnected||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;const key=e.key.toLowerCase();if('wasd'.includes(key)&&key.length===1){keys.add(key);e.preventDefault();return;}const actions={'1':()=>$('all').click(),'2':()=>$('workers').click(),i:()=>$('idle').click(),q:skill,f:()=>$('hero-skill').click(),e:()=>$('volley').click(),b:centerHome,' ':jumpAlert,m:()=>{mode='move';},r:()=>{mode='attack';},h:()=>$('hold').click(),escape:cancelMode,p:()=>$('start').click()};if(actions[key]){e.preventDefault();if(!e.repeat)actions[key]();}}
function keyup(e){keys.delete(e.key.toLowerCase());}function deactivate(){keys.clear();pointerInside=false;drag=null;}function activate(e){active=root.contains(e.target);if(!active)deactivate();}document.addEventListener('pointerdown',activate);document.addEventListener('keydown',keydown);document.addEventListener('keyup',keyup);window.addEventListener('blur',deactivate);document.addEventListener('visibilitychange',deactivate);
function restore(e){const c=e.detail?.globals?.widgetState?.modelContent?.clan;if(!game.started&&Number.isInteger(c)&&c>=0&&c<4&&player!==c){player=c;$('clan').value=c;reset();}}window.addEventListener('openai:set_globals',restore);

$('menu').onclick=()=>{$('menu-panel').hidden=!$('menu-panel').hidden;$('menu').setAttribute('aria-expanded',String(!$('menu-panel').hidden));};$('retreat').onclick=()=>{game.issue([...selected],'move',STARTS[player]);message('ถอยกลับฐาน');};$('select-visible').onclick=()=>choose(game.warriors());$('army-cancel').onclick=()=>{game.issue([...selected],'hold');cancelMode();};

$('upgrade').onclick=openTech;
$('upgrade-building').onclick=()=>{const u=game.warriors().filter(u=>game.trainingRecipe(u,selectedBuilding?.kind)?.tier>1).sort((a,b)=>dist(a,selectedBuilding)-dist(b,selectedBuilding))[0];if(!u)return;const result=game.train(selectedBuilding,[u.id]);message(result.ok?'ส่งทหารเข้าโรงฝึกเพื่อเลื่อนขั้น':result.reason);updateUI();};

function updateTrainingOptions(list){
  const transformed=list.find(u=>u.form),form=transformed&&ASCENSIONS[transformed.team];$('form-info').hidden=!form;
  if(form){$('form-info').textContent=(transformed.tier===4?form.hero:form.name)+' · ร่างถาวร\n'+form.passive+(transformed.awakened>0?'\nพลังตื่น '+Math.ceil(transformed.awakened)+' วินาที':'');}

  $('upgrade').textContent='เปิดสายพัฒนา · ดูวิชาและเงื่อนไขทุกขั้น';$('upgrade').disabled=false;
  const items=game.trainingOptions(list.map(u=>u.id));
  const key=items.map(i=>i.kind+':'+i.u.id+':'+i.d.name+':'+i.reason+':'+i.b?.id).join('|');if($('training-options').dataset.key!==key){$('training-options').dataset.key=key;$('training-options').innerHTML=items.map(({kind,d,b,u,enabled,missing,reason})=>'<button class="cursor-interaction" data-kind="'+kind+'" data-unit="'+u.id+'" '+(!enabled?'disabled':'')+'><b>↑ '+d.name+' · ขั้น '+d.tier+' · 1 คน</b><small>'+d.rice+' ข้าว / '+d.water+' น้ำ · '+d.seconds+' วิ</small><small>'+(reason||BUILDINGS[kind].name+' · ส่งทหารที่เลือกเข้าโรงฝึก')+'</small></button>'+(missing?'<button class="cursor-interaction" data-build-school="'+kind+'">เลือกชาวบ้านเพื่อสร้าง'+BUILDINGS[kind].name+'</button>':'')).join('');}
  const army=list.filter(u=>!u.worker),priorities=new Set(army.map(u=>u.targetPriority||'auto'));
  $('target-priority').value=priorities.size===1?[...priorities][0]:'mixed';
  $('target-priority').disabled=!game.running||game.over||!army.length;
  $('training-hint').textContent=army.some(u=>u.tier===3)?'ขั้น 3 → หอจอมทัพ → ขั้น 4 · 150 ข้าว / 100 น้ำ · 24 วิ':army.length&&army.every(u=>u.tier===4)?'ขั้น 4 สูงสุดแล้ว · ใช้สกิลจอมทัพ F':army.some(u=>u.job?.type==='train')?'กำลังเข้าโรงฝึก · คลิกอาคารเพื่อดูคิว':'ฝึกทีละคน · เลือกกลุ่มได้ ระบบเลือกผู้ที่พร้อมเลื่อนขั้น';
  const hero=list.find(u=>u.tier===4);$('hero-skill').hidden=!hero;if(hero){$('hero-skill').textContent='F · '+HERO_SKILLS[hero.team]+(hero.heroCooldown>0?' · '+Math.ceil(hero.heroCooldown)+' วิ':' · พร้อมใช้');$('hero-skill').title=ASCENSIONS[hero.team].ability;$('hero-skill').disabled=!game.running||game.over||hero.heroCooldown>0;}
}
$('target-priority').onchange=()=>{const priority=$('target-priority').value;if(game.setTargetPriority([...selected],priority))message('เป้าหมาย: '+({auto:'อัตโนมัติ · โจมตีศัตรูทุกประเภท',units:'ทหารและชาวบ้าน · ข้ามอาคาร',buildings:'อาคารและป้อม · ข้ามคน'}[priority]));updateUI();};
$('training-options').onclick=e=>{const build=e.target.closest('[data-build-school]');if(build){const u=game.workers().find(u=>!u.job)||game.workers().find(u=>u.job?.type==='gather');if(!u){message('ต้องมีชาวบ้านที่พร้อมก่อสร้าง');return;}choose([u]);const kind=build.dataset.buildSchool,reason=game.buildRequirement(kind);if(reason){message(reason);return;}beginBuild(kind);return;}const button=e.target.closest('button[data-kind]');if(!button)return;const u=game.units.find(u=>u.id===Number(button.dataset.unit)),b=game.structures.filter(b=>b.kind===button.dataset.kind&&b.team===player&&b.complete&&b.hp>0&&b.queue.length<3).sort((a,b)=>dist(a,u)-dist(b,u))[0];if(!u)return;const result=game.train(b,[u.id]);if(result.ok){selectedBuilding=b;selected.clear();}message(result.ok?'กำลังเดินเข้า'+BUILDINGS[b.kind].name+' · ดูเวลาและคิวด้านล่าง':result.reason);updateUI();};
$('hero-skill').onclick=()=>{message(game.heroSkill([...selected])?'ใช้วิชาจอมทัพแล้ว':'สกิลยังไม่พร้อม หรือไม่มีเป้าหมายในระยะ');updateUI();};
$('tower-upgrade').onclick=()=>{const result=game.upgradeTower(selectedBuilding);message(result.ok?'ป้อมกำลังอัปเกรด':result.reason);updateUI();};
$('repair').onclick=()=>{const u=game.workers().find(u=>!u.job);if(u)game.repair(selectedBuilding,[u.id]);updateUI();};
$('crop-status').onclick=()=>{camera.center(game.resources.find(r=>r.id==='rice-'+player));};
let resumeAfterTech=false;
function openTech(){if(!$('tech').hidden)return;resumeAfterTech=game.running;if(!online?.active)game.running=false;$('start').disabled=true;const school=k=>game.structures.some(b=>b.team===player&&b.kind===k&&b.complete&&b.hp>0)?'✓ พร้อมใช้งาน':'○ ยังไม่ได้สร้าง';const card=(name,line,detail)=>'<div class="r-tech-card"><b>'+name+'</b>'+line+'<span>'+detail+'</span></div>';
 $('tech-content').innerHTML='<div class="r-tech-grid"><article class="r-tech-stage"><h3>01 · วิชาพื้นฐาน</h3>'+['dojo','archery','shrine'].map(k=>card(TRAINING[k].name,'ชาวบ้าน → '+BUILDINGS[k].name,TRAINING[k].rice+' ข้าว / '+TRAINING[k].water+' น้ำ · '+TRAINING[k].seconds+' วิ<br>'+school(k))).join('')+'</article><article class="r-tech-stage"><h3>02 · รวมสองวิชา</h3>'+Object.entries(COMBINATIONS).map(([key,d])=>card(d.name,key.split(',').map(k=>BUILDINGS[k].name).join(' + '),'85 ข้าว / 45 น้ำ · 14 วิ · ฝึกวิชาที่ยังไม่มี')).join('')+'</article><article class="r-tech-stage"><h3>03 · ร่างวิวัฒน์ถาวร</h3>'+card(ELITES[player],'ทหารขั้น 2 → สำนักวิชาที่สาม','110 ข้าว / 70 น้ำ · 18 วิ<br>'+ASCENSIONS[player].passive)+card('ครบทั้ง 3 วิชา','ดาบ + ธนู + วิญญาณ','ฝึกจบแล้วเปลี่ยนร่างจริง · ยูนิตเดิม · จำนวนประชากรเท่าเดิม')+'</article><article class="r-tech-stage"><h3>04 · จอมทัพ</h3>'+card(ASCENSIONS[player].hero,'ยอดฝีมือขั้น 3 → หอจอมทัพ','150 ข้าว / 100 น้ำ · 24 วิ<br>'+school('warhall'))+card('F · '+HERO_SKILLS[player],'วิชาจอมทัพ · คูลดาวน์ 30 วิ',ASCENSIONS[player].ability)+'</article></div><div class="r-tech-note"><b>ป้อมธนู I → II → III</b><p>สร้าง: 130 ข้าว / 80 น้ำ · ระยะ 300 → อัปเกรด II: 130 / 70 · ระยะ 350 → อัปเกรด III: 200 / 100 · ระยะ 400<br>เลือกชาวบ้านเพื่อสร้างป้อม คลิกป้อมเพื่ออัปเกรด ดูวงระยะยิง และส่งคนงานซ่อม</p></div>';
 $('tech-content').innerHTML+='<div class="r-ascension-intro"><b>สี่ตระกูล · สี่ร่างวิวัฒน์</b><p>ขั้น 3 เปลี่ยนร่างถาวร · ขั้น 4 เพิ่มพลังและปลดล็อก F · กระเรียนมีปีกแต่ยังเดินตามเส้นทางบนพื้น</p></div><div class="r-ascension-grid">'+ASCENSIONS.map((f,team)=>'<article class="r-ascension-card '+(team===player?'current':'')+'"><canvas width="120" height="120" data-form-team="'+team+'" aria-label="ร่าง'+f.name+'"></canvas><small>'+CLANS[team].name+(team===player?' · เผ่าของคุณ':'')+'</small><h3>'+f.name+'</h3><b>III → IV · '+f.hero+'</b><p>'+f.passive+'</p><p><strong>F</strong> '+f.ability+'</p></article>').join('')+'</div>';
 paintAscensionCards();$('tech').hidden=false;keys.clear();pointerInside=false;$('tech-close').focus();
}
function closeTech(){$('tech').hidden=true;if(!online?.active)game.running=resumeAfterTech&&!game.over;$('start').disabled=game.over||!!online?.active;$('tech-open').focus();}
$('tech-open').onclick=openTech;$('tech-close').onclick=closeTech;
$('showcase').onclick=()=>{if(online?.active)return;reset();game.setupShowcase();game.started=true;game.running=true;$('start').textContent='พัก [P]';$('clan').disabled=true;$('intro').hidden=true;choose(game.warriors().filter(u=>u.tier>=3));camera.zoom=1.15;centerHome();message('ร่างวิวัฒน์พร้อม · ขั้น 3 และ 4 · คลิกยูนิตดูความสามารถ · กด F ใช้พลังจอมทัพ · เปิดเมนูเพื่อทดสอบศัตรูบุก');updateUI();};
