// Paddy appearance follows the same finite stock and growth clock as harvesting.
function drawRiceField(r){
  const ripe=r.stage==='ripe',growth=r.stage==='growing'?1-r.cycle/RICE_CYCLE.growing:0;
  ctx.save();ctx.translate(r.x,r.y);
  const corners=[[-110,-4],[8,-68],[112,9],[-8,74]];
  ctx.beginPath();corners.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();
  const mud=ctx.createLinearGradient(0,-68,0,74);mud.addColorStop(0,'#394235');mud.addColorStop(.5,'#5b5135');mud.addColorStop(1,'#3c3627');ctx.fillStyle=mud;ctx.fill();ctx.strokeStyle='#948154';ctx.lineWidth=3;ctx.stroke();
  ctx.save();ctx.clip();for(let i=0;i<150;i++){const x=((i*73)%227)-112,y=((i*47)%143)-68;ctx.fillStyle=i%3?'#aea08033':'#171e1766';ctx.fillRect(x,y,2+i%4,1);}
  for(let row=0;row<6;row++){ctx.strokeStyle='#80908255';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-96+row*15,0-row*9);ctx.lineTo(16+row*15,49-row*9);ctx.stroke();}ctx.restore();
  const patches=Array.from({length:RICE_PATCHES},(_,i)=>({i,p:ricePatchPoint(r,i)})).sort((a,b)=>a.p.y-b.p.y);
  for(const {i,p} of patches){const x=p.x-r.x,y=p.y-r.y,fill=ripe?clamp((r.patches[i]||0)/(r.max/RICE_PATCHES),0,1):growth;
    ellipse(ctx,x,y+1,8,3,'#15241f88');
    // Each clump disappears at the point where a worker cuts it; stubble stays behind.
    const stalks=ripe?Math.ceil(fill*7):growth>0?7:0;
    for(let k=0;k<7;k++){const px=x+(k-3)*1.8,py=y+(k%3)*.9;ctx.strokeStyle='#998151';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(px-1,py-3);ctx.stroke();if(k>=stalks)continue;
      const height=ripe?19+(i+k)%7:3+growth*21,sway=Math.sin(game.t*1.9+i*.7+k)*1.2*(ripe?1:growth);
      ctx.strokeStyle=ripe?'#748342':'#619451';ctx.lineWidth=1.05;ctx.beginPath();ctx.moveTo(px,py);ctx.quadraticCurveTo(px-2,py-height*.6,px+sway,py-height);ctx.moveTo(px,py-4);ctx.quadraticCurveTo(px-8,py-height*.7,px-4+sway,py-height*.85);ctx.moveTo(px,py-6);ctx.quadraticCurveTo(px+8,py-height*.65,px+5+sway,py-height*.9);ctx.stroke();
      if(ripe||growth>.85){ctx.strokeStyle='#d6bd72';ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(px+sway,py-height);ctx.quadraticCurveTo(px+5+sway,py-height-1,px+6+sway,py-height+5);ctx.stroke();}
    }
    if(r.lastHarvest?.patch===i&&game.t-r.lastHarvest.t<.35){ctx.strokeStyle='#f9e0a8';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y-8,11,Math.PI,Math.PI*1.8);ctx.stroke();}
  }
  const remaining=r.patches.filter(n=>n>.001).length,label=ripe?'นาข้าว '+Math.ceil(r.amount)+' / '+r.max+' · เหลือ '+remaining+'/48 กอ':r.stage==='fallow'?'เกี่ยวหมดแล้ว · พักดิน '+Math.ceil(r.cycle)+' วิ':'ต้นกล้างอกใหม่ · '+Math.ceil(r.cycle)+' วิ';
  ctx.font='11px "Noto Sans Thai",sans-serif';ctx.textAlign='center';const width=ctx.measureText(label).width+18;ctx.fillStyle='#071a12ee';ctx.fillRect(-width/2,82,width,24);ctx.fillStyle=ripe?'#efd580':'#a9d987';ctx.fillText(label,0,98);
  ctx.fillStyle='#243d2a';ctx.fillRect(-65,110,130,4);ctx.fillStyle=ripe?'#dec269':'#81ba6a';ctx.fillRect(-65,110,130*(ripe?r.amount/r.max:growth),4);ctx.restore();
}
function inView(p,margin=130){return p.x>camera.x-margin&&p.y>camera.y-margin&&p.x<camera.x+camera.w/camera.zoom+margin&&p.y<camera.y+camera.h/camera.zoom+margin;}
function drawResource(r){if(pondReady&&r.type==='water'&&!r.buildingId){ctx.drawImage(pondArt,r.visualX-89,r.visualY-75,178,119);return;}if(r.type==='rice'){drawRiceField(r);return;}if(r.buildingId)return;if(r.type==='water'){const x=r.visualX,y=r.visualY;ellipse(ctx,x+2,y+4,68,47,'#283f2e');ellipse(ctx,x,y,59,39,'#526856');ellipse(ctx,x,y-2,52,32,'#365e65');ellipse(ctx,x-8,y-7,35,20,'#548480');ctx.strokeStyle='#acd0bf77';ctx.lineWidth=1.5;for(let i=0;i<6;i++){ctx.beginPath();ctx.ellipse(x-20+i*8,y-8+i%2*9,9,3,0,0,Math.PI);ctx.stroke();}ctx.fillStyle='#d1dec5';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText('แหล่งน้ำ',x,y+64);return;}
  ctx.save();ctx.translate(r.x,r.y);ellipse(ctx,4,11,103,63,'#223a2477');ctx.fillStyle='#665933';ctx.beginPath();ctx.moveTo(-90,-49);ctx.lineTo(84,-48);ctx.lineTo(97,53);ctx.lineTo(-87,55);ctx.closePath();ctx.fill();ctx.strokeStyle='#b8a567';ctx.lineWidth=3;ctx.stroke();const growth=r.amount/r.max;for(let row=0;row<7;row++){ctx.fillStyle='#364932';ctx.fillRect(-82,-42+row*13,169,4);for(let col=0;col<15;col++){const x=-75+col*11,y=-35+row*13,plant=6+growth*13;ctx.strokeStyle=growth>.5?'#c4bf69':'#6f984e';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x,y+6);ctx.lineTo(x+1,y-plant);ctx.moveTo(x,y);ctx.lineTo(x-5,y-plant*.6);ctx.moveTo(x+1,y-5);ctx.lineTo(x+7,y-plant*.7);ctx.stroke();if(growth>.5)ellipse(ctx,x+2,y-plant,2,3,'#ddc87e');}}ctx.font='12px system-ui';ctx.fillStyle='#e5d69a';ctx.textAlign='center';ctx.fillText('นาข้าว · '+Math.floor(r.amount),0,77);ctx.restore();}
function drawStructure(b,ghost=false){if(b.kind==='tower'&&b.hp>0&&(ghost||selectedBuilding?.id===b.id)){ctx.save();ctx.strokeStyle='#d5c17e88';ctx.fillStyle='#d5c17e0b';ctx.lineWidth=1.5;ctx.setLineDash([7,7]);ctx.beginPath();ctx.arc(b.x,b.y,TOWER_LEVELS[b.level||1].range,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();}if(richBuilding(b,ghost))return;if(b.kind==='hq'){drawBase(b);return;}const d=BUILDINGS[b.kind],c=CLANS[b.team];ctx.save();ctx.translate(b.x,b.y);if(b.hp<=0){ellipse(ctx,0,8,d.w*.55,23,'#283228');ctx.fillStyle='#776548';ctx.fillRect(-24,-6,22,12);ctx.fillRect(6,3,25,10);ctx.restore();return;}
  if(!b.complete&&!ghost){ellipse(ctx,0,9,d.w*.65,d.h*.45,'#a28c5066');ctx.strokeStyle='#ccb77b';ctx.lineWidth=2;ctx.strokeRect(-d.w/2,-d.h/2,d.w,d.h);for(let i=-1;i<=1;i++){ctx.strokeStyle='#75512f';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(i*d.w*.4,16);ctx.lineTo(i*d.w*.4,-40-b.progress*30);ctx.stroke();}ctx.strokeStyle='#bea078';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-d.w*.5,-20);ctx.lineTo(d.w*.5,-54);ctx.moveTo(-d.w*.5,-54);ctx.lineTo(d.w*.5,-20);ctx.stroke();ctx.fillStyle='#22392a';ctx.fillRect(-40,-80,80,5);ctx.fillStyle='#e2c579';ctx.fillRect(-40,-80,80*b.progress,5);ctx.fillStyle='#eee3bd';ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillText('สร้าง '+Math.floor(b.progress*100)+'%',0,43);ctx.restore();return;}
  ellipse(ctx,8,13,d.w*.65,d.h*.4,'#0d211b88');if(b.kind==='well'){ellipse(ctx,0,5,29,17,'#a09c79');ellipse(ctx,0,-2,27,17,'#c3b792');ellipse(ctx,0,-3,17,10,'#315d67');ctx.fillStyle='#685035';ctx.fillRect(-27,-52,5,59);ctx.fillRect(22,-52,5,59);ctx.fillRect(-29,-54,58,5);ctx.strokeStyle='#ccb078';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-49);ctx.lineTo(0,-8);ctx.stroke();ctx.fillStyle='#a58a54';ctx.fillRect(-7,-15,14,12);}
  else if(b.kind==='tower'){ctx.fillStyle='#70654c';ctx.fillRect(-23,-54,46,68);ctx.fillStyle='#a39a76';ctx.fillRect(-18,-55,36,59);ctx.fillStyle='#514a32';for(let i=0;i<3;i++)ctx.fillRect(-20+i*16,-70,10,23);roof(0,-58,46,30,c.dark,c.color);ctx.fillStyle='#282e22';ctx.fillRect(-5,-42,10,16);}
  else{const half=d.w*.42;ctx.fillStyle='#68543a';ctx.fillRect(-half,-26,half*2,48);ctx.fillStyle='#a38c61';ctx.fillRect(-half+5,-27,half*2-10,45);ctx.strokeStyle='#705a3b';ctx.lineWidth=2;for(let i=-half+7;i<half;i+=12){ctx.beginPath();ctx.moveTo(i,-24);ctx.lineTo(i,17);ctx.stroke();}ctx.fillStyle='#253020';ctx.fillRect(-11,-5,22,28);roof(0,-24,half+19,b.kind==='hut'?35:42,b.kind==='hut'?'#a38b4c':c.dark,b.kind==='hut'?'#d4bd7a':c.color);if(b.kind==='dojo'){ctx.strokeStyle='#d5c7a0';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-24,-7);ctx.lineTo(-10,-28);ctx.moveTo(-24,-28);ctx.lineTo(-10,-7);ctx.stroke();}if(b.kind==='archery'){ctx.strokeStyle='#d7c38a';ctx.lineWidth=3;ctx.beginPath();ctx.arc(26,-2,12,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#903b2a';ctx.beginPath();ctx.arc(26,-2,5,0,Math.PI*2);ctx.fill();}if(b.kind==='store'){for(let i=0;i<3;i++){ellipse(ctx,-24+i*18,21,10,14,'#baa270');ctx.strokeStyle='#675e36';ctx.beginPath();ctx.moveTo(-32+i*18,14);ctx.lineTo(-16+i*18,14);ctx.stroke();}}}
  if(selectedBuilding?.id===b.id&&!ghost){ctx.strokeStyle='#e8cf82';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,8,d.w*.65,d.h*.5,0,0,Math.PI*2);ctx.stroke();}if(!ghost){ctx.fillStyle='#10251b';ctx.fillRect(-32,-94,64,4);ctx.fillStyle=c.color;ctx.fillRect(-32,-94,64*b.hp/b.max,4);ctx.font='11px system-ui';ctx.fillStyle='#eee0b7';ctx.textAlign='center';ctx.fillText(d.name,0,d.h*.5+20);if(b.queue?.length){ctx.fillStyle='#d4bd75';ctx.fillText('ฝึก '+b.queue.length+' คน',0,d.h*.5+35);}}ctx.restore();}
function roof(x,y,half,height,dark,light){ctx.fillStyle=dark;ctx.beginPath();ctx.moveTo(x-half,y);ctx.lineTo(x-half*.65,y-height*.65);ctx.lineTo(x,y-height);ctx.lineTo(x+half*.65,y-height*.65);ctx.lineTo(x+half,y);ctx.lineTo(x,y-height*.25);ctx.closePath();ctx.fill();ctx.strokeStyle=light;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-half,y);ctx.lineTo(x,y-height*.25);ctx.lineTo(x+half,y);ctx.stroke();}
function drawWorker(u){if(richUnit(u))return;ctx.save();ctx.translate(u.x,u.y);const c=CLANS[u.team];if(u.hp<=0){ctx.globalAlpha=Math.max(0,.6-(game.t-u.deadAt)/18);ellipse(ctx,0,0,12,4,'#263329');ctx.restore();return;}ellipse(ctx,2,2,12,5,'#12241b99');if(selected.has(u.id)){ctx.strokeStyle='#e5d392';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(0,2,15,7,0,0,Math.PI*2);ctx.stroke();}const stride=Math.sin(u.walk)*3;ctx.strokeStyle='#413928';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-3,-6);ctx.lineTo(-4+stride,2);ctx.moveTo(3,-6);ctx.lineTo(4-stride,2);ctx.stroke();ctx.fillStyle=u.flash?'#f9e3b7':'#a69c74';ctx.fillRect(-7,-23,14,17);ctx.fillStyle=c.dark;ctx.fillRect(-8,-9,16,5);ellipse(ctx,0,-29,5,6,'#d4b084');ctx.fillStyle='#c5b274';ctx.beginPath();ctx.moveTo(-13,-29);ctx.lineTo(0,-41);ctx.lineTo(14,-29);ctx.closePath();ctx.fill();ctx.strokeStyle='#8a7948';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-13,-29);ctx.lineTo(14,-29);ctx.stroke();if(u.cargo>0){if(u.cargoType==='rice'){ellipse(ctx,9,-13,7,10,'#cbb27a');ctx.strokeStyle='#8c773e';ctx.beginPath();ctx.moveTo(5,-19);ctx.lineTo(12,-19);ctx.stroke();}else{ctx.fillStyle='#759faa';ctx.fillRect(6,-12,11,10);ctx.strokeStyle='#ceb987';ctx.strokeRect(7,-18,9,9);}}else{ctx.strokeStyle='#c5b681';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(8,-11);ctx.lineTo(17,-25);ctx.stroke();ctx.strokeStyle='#d8d5b9';ctx.beginPath();ctx.arc(16,-26,7,-2.8,-.2);ctx.stroke();}ctx.fillStyle='#12251b';ctx.fillRect(-12,-47,24,3);ctx.fillStyle='#a8ca97';ctx.fillRect(-12,-47,24*u.hp/u.max,3);ctx.restore();}
function drawPortrait(item){if(richPortrait(item))return;const c=CLANS[item?.team??player],g=pc.createLinearGradient(0,0,120,132);g.addColorStop(0,'#3b4d33');g.addColorStop(1,'#101f19');pc.fillStyle=g;pc.fillRect(0,0,120,132);pc.strokeStyle='#a68b4d';pc.lineWidth=1;pc.strokeRect(5,5,110,122);if(!item){pc.font='42px serif';pc.fillStyle='#d4be82';pc.textAlign='center';pc.fillText('四',60,84);return;}if(item.building){pc.fillStyle='#ab9867';pc.fillRect(29,65,62,40);pc.fillStyle='#293024';pc.fillRect(51,82,18,23);pc.fillStyle=c.dark;pc.beginPath();pc.moveTo(16,67);pc.lineTo(60,31);pc.lineTo(104,67);pc.closePath();pc.fill();pc.strokeStyle='#d8bf79';pc.lineWidth=3;pc.stroke();pc.fillStyle='#e4d5a3';pc.font='12px system-ui';pc.textAlign='center';pc.fillText(item.kind==='hq'?'ศาลาบัญชาการ':BUILDINGS[item.kind].name,60,120);return;}
  const worker=item.worker;pc.fillStyle=worker?'#9e9470':c.dark;pc.beginPath();pc.moveTo(12,130);pc.lineTo(22,91);pc.lineTo(43,82);pc.lineTo(79,82);pc.lineTo(101,94);pc.lineTo(112,132);pc.fill();pc.fillStyle=worker?'#c2b18a':c.color;pc.beginPath();pc.moveTo(37,85);pc.lineTo(57,111);pc.lineTo(67,93);pc.lineTo(83,83);pc.lineTo(73,132);pc.lineTo(39,132);pc.fill();pc.fillStyle='#b5885f';pc.fillRect(49,75,23,23);const face=pc.createLinearGradient(36,45,84,77);face.addColorStop(0,'#e2c198');face.addColorStop(1,'#a27750');ellipse(pc,60,61,23,31,face);pc.fillStyle='#34342a';pc.fillRect(41,54,11,3);pc.fillRect(67,54,11,3);pc.fillStyle='#343228';pc.fillRect(46,61,4,3);pc.fillRect(70,61,4,3);pc.strokeStyle='#8b5a40';pc.lineWidth=2;pc.beginPath();pc.moveTo(59,63);pc.lineTo(56,76);pc.lineTo(63,76);pc.moveTo(51,85);pc.lineTo(69,85);pc.stroke();if(worker){pc.fillStyle='#b49a59';pc.beginPath();pc.moveTo(6,54);pc.lineTo(59,14);pc.lineTo(115,54);pc.closePath();pc.fill();pc.strokeStyle='#dbc18a';pc.lineWidth=3;pc.beginPath();pc.moveTo(6,54);pc.lineTo(115,54);pc.stroke();pc.strokeStyle='#8d793f';pc.lineWidth=1;for(let i=0;i<7;i++){pc.beginPath();pc.moveTo(59,15);pc.lineTo(9+i*17,53);pc.stroke();}}else{pc.fillStyle=item.team===0?'#b6a879':c.dark;pc.beginPath();pc.moveTo(34,53);pc.lineTo(35,31);pc.lineTo(60,18);pc.lineTo(85,31);pc.lineTo(87,53);pc.lineTo(70,46);pc.lineTo(60,31);pc.lineTo(50,47);pc.closePath();pc.fill();pc.strokeStyle='#e7d394';pc.lineWidth=3;pc.beginPath();pc.moveTo(60,20);pc.lineTo(60,39);pc.stroke();}}
function draw(){if(!game)return;paintFog();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#09170f';ctx.fillRect(0,0,camera.w,camera.h);ctx.save();ctx.scale(camera.zoom,camera.zoom);ctx.translate(-camera.x,-camera.y);ctx.drawImage(terrain,0,0);for(const r of game.resources)if(inView(r))drawResource(r);for(const z of game.zones)if(game.visibleAt(z)){ellipse(ctx,z.x,z.y,z.r,z.r,'#a0ca6544');ctx.strokeStyle='#c7e995';ctx.beginPath();ctx.arc(z.x,z.y,z.r,0,Math.PI*2);ctx.stroke();}
  const objects=[...game.structures.filter(b=>b.team===player||game.visibleAt(b)),...game.units.filter(u=>!u.inTraining&&(u.team===player||game.visibleAt(u)))].filter(u=>inView(u)).sort((a,b)=>a.y-b.y);for(const u of objects)u.building?drawStructure(u):u.worker?drawWorker(u):drawUnit(u);
  for(const p of game.projectiles)if(game.visibleAt(p)&&inView(p)){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle||0);if(p.form==='naga'||p.form==='crane'){const color=p.form==='naga'?'#9bef72':'#b8eeff';ctx.shadowColor=color;ctx.shadowBlur=8;ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(0,0,5,3,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(-13,0);ctx.lineTo(-4,0);ctx.stroke();}else{ctx.strokeStyle='#f3d7a1';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-12,0);ctx.lineTo(3,0);ctx.stroke();}ctx.restore();}for(const e of game.effects){if(!game.visibleAt(e)||!inView(e))continue;const t=1-e.life/e.max;ctx.save();ctx.globalAlpha=Math.min(1,e.life*4);ctx.strokeStyle=e.color;ctx.fillStyle=e.color;ctx.lineWidth=2;ctx.beginPath();if(e.type==='ascend'){ctx.lineWidth=2.5;ctx.ellipse(e.x,e.y-15,20+t*35,12+t*18,0,0,Math.PI*2);ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4+t*2;ctx.fillRect(e.x+Math.cos(a)*(15+t*30),e.y-15-Math.sin(a)*(10+t*18)-t*48,3,6);}ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText(e.text,e.x,e.y-90-t*15);}else if(e.type==='text'){ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(e.text,e.x,e.y-t*23);}else if(e.type==='dash'){ctx.lineWidth=6;ctx.moveTo(e.x,e.y);ctx.lineTo(e.tx,e.ty);ctx.stroke();}else if(e.type==='slash'){ctx.arc(e.x,e.y-12,20,-2+t,1+t);ctx.stroke();}else{ctx.arc(e.x,e.y,(e.type==='heal'?180:30)*t+2,0,Math.PI*2);ctx.stroke();}ctx.restore();}ctx.imageSmoothingEnabled=true;ctx.drawImage(fog,0,0,W,H);
  if(buildKind&&mouse.x>=0){const result=game.placement(buildKind,camera.world(mouse)),d=BUILDINGS[buildKind],p=result.point||camera.world(mouse);ctx.save();ctx.globalAlpha=.6;drawStructure({kind:buildKind,team:player,...p,hp:d.hp,max:d.hp,complete:true,queue:[]},true);ctx.restore();ctx.fillStyle=result.ok?'#87caa14a':'#e779644a';ctx.strokeStyle=result.ok?'#b5f5c3':'#ff8f74';ctx.lineWidth=2;ctx.fillRect(p.x-d.w/2,p.y-d.h/2,d.w,d.h);ctx.strokeRect(p.x-d.w/2,p.y-d.h/2,d.w,d.h);$('placement').hidden=false;$('placement').textContent=result.ok?d.name+' · '+d.rice+' ข้าว / '+d.water+' น้ำ · คลิกเพื่อสร้าง':result.reason+' · Esc ยกเลิก';}else if(!buildKind)$('placement').hidden=true;
  if(mode==='poison'&&own().length){const u=own().find(u=>!u.worker&&!u.ranged)||own()[0],p=camera.world(mouse);ctx.strokeStyle='#d4e99a99';ctx.setLineDash([5,7]);ctx.beginPath();ctx.arc(u.x,u.y,230,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(p.x,p.y,85,0,Math.PI*2);ctx.stroke();}ctx.restore();if(drag?.kind==='select'&&dist(drag.start,drag.end)>7){ctx.fillStyle='#dfd29822';ctx.strokeStyle='#f0dda0';ctx.fillRect(drag.start.x,drag.start.y,drag.end.x-drag.start.x,drag.end.y-drag.start.y);ctx.strokeRect(drag.start.x,drag.start.y,drag.end.x-drag.start.x,drag.end.y-drag.start.y);}drawMini();}
function drawMini(){mc.clearRect(0,0,240,180);mc.drawImage(terrain,0,0,240,180);for(const r of game.resources){if(!game.seen[world.cell(r)])continue;mc.fillStyle=r.type==='rice'?'#d2be65':'#75b9c3';mc.fillRect(r.x/W*240-3,r.y/H*180-2,6,4);}mc.globalAlpha=.82;mc.drawImage(fog,0,0,240,180);mc.globalAlpha=1;for(let i=0;i<4;i++){const b=STARTS[i],x=b.x/W*240,y=b.y/H*180;mc.strokeStyle='#adb5a0';mc.strokeRect(x-5,y-5,10,10);mc.font='9px system-ui';mc.fillStyle='#d9d7b9';mc.fillText('P'+(i+1),x-6,y-9);}for(const b of game.structures){if(b.hp<=0||b.team!==player&&!game.visibleAt(b))continue;mc.fillStyle=b.team===player?'#b3e7c9':'#f78770';mc.fillRect(b.x/W*240-3,b.y/H*180-3,6,6);}for(const u of game.alive()){if(u.team!==player&&!game.visibleAt(u))continue;mc.fillStyle=u.team===player?u.worker?'#e5d493':'#b1ecd1':'#ff725f';mc.beginPath();mc.arc(u.x/W*240,u.y/H*180,1.7,0,Math.PI*2);mc.fill();}for(const a of game.alerts){if(game.t-a.t>14)continue;mc.strokeStyle='#ff654c';mc.lineWidth=2;mc.globalAlpha=.5+Math.abs(Math.sin(game.t*6))*.5;mc.beginPath();mc.arc(a.x/W*240,a.y/H*180,7+(game.t*1.6)%1*9,0,Math.PI*2);mc.stroke();mc.globalAlpha=1;}mc.strokeStyle='#ffe8b2';mc.lineWidth=1.5;mc.strokeRect(camera.x/W*240,camera.y/H*180,camera.w/camera.zoom/W*240,camera.h/camera.zoom/H*180);}
function resize(){const r=canvas.getBoundingClientRect();camera.w=r.width;camera.h=r.height;dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);camera.clamp();draw();}
function cleanup(){observer.disconnect();document.removeEventListener('pointerdown',activate);document.removeEventListener('keydown',keydown);document.removeEventListener('keyup',keyup);window.removeEventListener('blur',deactivate);document.removeEventListener('visibilitychange',deactivate);window.removeEventListener('openai:set_globals',restore);soundContext?.close().catch(()=>{});}
function loop(now){if(!root.isConnected){cleanup();return;}const dt=last?Math.min((now-last)/1000,.05):0;last=now;if(!document.hidden){let x=(keys.has('d')?1:0)-(keys.has('a')?1:0),y=(keys.has('s')?1:0)-(keys.has('w')?1:0);if(pointerInside&&!drag&&!mode&&mouse.x>=0&&mouse.y>=0&&mouse.x<=camera.w&&mouse.y<=camera.h){const edge=18;if(mouse.x<edge)x--;if(mouse.x>camera.w-edge)x++;if(mouse.y<edge)y--;if(mouse.y>camera.h-edge)y++;}camera.x+=x*560*dt/camera.zoom;camera.y+=y*560*dt/camera.zoom;camera.clamp();if(!online?.active||online.inMatch)game.step(dt);draw();uiElapsed+=dt;if(uiElapsed>.15){updateUI();uiElapsed=0;}}requestAnimationFrame(loop);}
const observer=new ResizeObserver(resize);reset();resize();centerHome();observer.observe(canvas);requestAnimationFrame(loop);
